project:
  type: book
  output-dir: docs

book:
  title: "Kenai Peninsula Borough Fish Passage Prioritization Data Synthesis [DRAFT]"
  author: "Benjamin Meyer, Kenai Watershed Forum"
  page-navigation: true
  chapters:
    - index.qmd
    - methods.qmd
    - results.qmd
    - discussion.qmd
    #- references.qmd
    
  repo-url: https://github.com/Kenai-Watershed-Forum/fish-passage-prioritization
  repo-actions: [edit]
  search: true
  downloads: [docx]  

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-fold: true
    code-summary: "Show the code"
    prefer-html: true
  #pdf:
  #  documentclass: scrreprt
  docx:
    toc: true
    toc-depth: 2
    toc-title: Table of contents
    number-sections: true
    highlight-style: github

editor: visual



